[package]
name = "conjure"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
git2 = { version = "0.21.0", features = ["https", "ssh"] }
kdl = { version =  "6.7.1", features = ["serde"] }
miette = { version = "7.6.0", features = ["fancy"] }
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
tokio = "1.53.1"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
