[package]
name = "conjure"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
git2 = { version = "0.21.0", features = ["https", "ssh"] }
indicatif = { version = "0.18.6", features = ["improved_unicode", "rayon"] }
kdl = { version =  "6.7.1", features = ["serde"] }
miette = { version = "7.6.0", features = ["fancy"] }
owo-colors = "4.3.0"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
